package com.bloomtech.springboot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// this was generated by the SpringInitializer
// DO NOT CHANGE THIS CODE

@SpringBootApplication // tells the server this is a spring boot app
public class FirstSpringBootAppApplication {

	public static void main(String[] args) {
		// start the server with this class
		SpringApplication.run(FirstSpringBootAppApplication.class, args);
	}

}
